apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-v1
  labels:
    app: backend-app
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
      version: v1
  template:
    metadata:
      labels:
        app: backend-app
        version: v1
    spec:
      containers:
        - name: backend-app
          image: nrt.ocir.io/orasejapan/codeatcustomer/backend-app-apm:helidon4
          ports:
            - containerPort: 8081
          env:
            - name: tracing.data-upload-endpoint
              valueFrom:
                secretKeyRef:
                  name: apm-secret
                  key: endpoint
            - name: tracing.private-data-key
              valueFrom:
                secretKeyRef:
                  name: apm-secret
                  key: private-key
            - name: SERVICE_VERSION
              value: V1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-v2
  labels:
    app: backend-app
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
      version: v2
  template:
    metadata:
      labels:
        app: backend-app
        version: v2
    spec:
      containers:
        - name: backend-app
          image: nrt.ocir.io/orasejapan/codeatcustomer/backend-app-apm:helidon4
          ports:
            - containerPort: 8081
          env:
            - name: tracing.data-upload-endpoint
              valueFrom:
                secretKeyRef:
                  name: apm-secret
                  key: endpoint
            - name: tracing.private-data-key
              valueFrom:
                secretKeyRef:
                  name: apm-secret
                  key: private-key
            - name: SERVICE_VERSION
              value: V2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-v3
  labels:
    app: backend-app
    version: v3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
      version: v3
  template:
    metadata:
      labels:
        app: backend-app
        version: v3
    spec:
      containers:
        - name: backend-app
          image: nrt.ocir.io/orasejapan/codeatcustomer/backend-app-apm:helidon4
          ports:
            - containerPort: 8081
          env:
            - name: tracing.data-upload-endpoint
              valueFrom:
                secretKeyRef:
                  name: apm-secret
                  key: endpoint
            - name: tracing.private-data-key
              valueFrom:
                secretKeyRef:
                  name: apm-secret
                  key: private-key
            - name: SERVICE_VERSION
              value: V3
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: backend-app
