apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-v1
  labels:
    app: backend-app
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
      version: v1
  template:
    metadata:
      labels:
        app: backend-app
        version: v1
    spec:
      containers:
      - name: backend-app
        image: nrt.ocir.io/orasejapan/codeatcustomer/backend-app-v1
        # image: nrt.ocir.io/orasejapan/codeatcustomer/backend-app-v1-apm
        ports:
        - containerPort: 8081
        # env:
        # - name: tracing.data-upload-endpoint
        #   value: https://aaaac7cn6krzmaaaaaaaaaavde.apm-agt.us-ashburn-1.oci.oraclecloud.com
        # - name: tracing.private-data-key
        #   value: TOQXOGDUZEEUXHNSTKNK5BVSZBTF4Z63
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-v2
  labels:
    app: backend-app
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
      version: v2
  template:
    metadata:
      labels:
        app: backend-app
        version: v2
    spec:
      containers:
      - name: backend-app
        image: nrt.ocir.io/orasejapan/codeatcustomer/backend-app-v2
        # image: nrt.ocir.io/orasejapan/codeatcustomer/backend-app-v2-apm
        ports:
        - containerPort: 8081
        # env:
        # - name: tracing.data-upload-endpoint
        #   value: https://aaaac7cn6krzmaaaaaaaaaavde.apm-agt.us-ashburn-1.oci.oraclecloud.com
        # - name: tracing.private-data-key
        #   value: TOQXOGDUZEEUXHNSTKNK5BVSZBTF4Z63
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-v3
  labels:
    app: backend-app
    version: v3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
      version: v3
  template:
    metadata:
      labels:
        app: backend-app
        version: v3
    spec:
      containers:
      - name: backend-app
        image: nrt.ocir.io/orasejapan/codeatcustomer/backend-app-v3
        # image: nrt.ocir.io/orasejapan/codeatcustomer/backend-app-v3-apm
        ports:
        - containerPort: 8081
        # env:
        # - name: tracing.data-upload-endpoint
        #   value: https://aaaac7cn6krzmaaaaaaaaaavde.apm-agt.us-ashburn-1.oci.oraclecloud.com
        # - name: tracing.private-data-key
        #   value: TOQXOGDUZEEUXHNSTKNK5BVSZBTF4Z63
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app
spec:
  type: ClusterIP 
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  selector:
    app: backend-app